{{- if .Values.appConfig }}
apiVersion: v1
data:
  application.yml: |-
    {{- toYaml .Values.appConfig | nindent 4 }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "ocp-deployment.labels" . | nindent 4 }}
{{- end }}
