{{- if .Values.externalSecrets }}
{{- range .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .secretName }}
spec:
  externalSecretSpec:
    data:
{{- range .secretKeys }}
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: {{ .externalKey }}
        secretKey: {{ .localKey }}
{{- end }}
    dataFrom:
      - {}
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: {{ $.Values.externalSecrets.clusterStore }}
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ $.Release.Namespace }}
  refreshTime: 1m
{{- end }}
{{- end }}
