apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ocp-deployment.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ocp-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
{{- if .Values.appConfig }}
        configmap-checksum: {{ include (print $.Template.BasePath "/app-config.yaml") . | sha256sum }}
{{- end }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ocp-deployment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ocp-deployment.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.appConfig }}
          volumeMounts:
          - name: {{ .Release.Name }}-appconfig-volume
            mountPath: /app/configs
{{- end }}         
          env:
            - name: APP_NAME
              value: {{ .Release.Name }}
{{- if .Values.appConfig }}
            - name: SPRING_CONFIG_LOCATION
              value: /app/configs/application.yml
            - name: JAVA_INITIAL_MEM_RATIO
              value: "40"
            - name: JAVA_MAX_MEM_RATIO
              value: "75"
{{- end }}
{{- if .Values.appConfig }}
      volumes:
      - name: {{ .Release.Name }}-appconfig-volume
        configMap:
          name: {{ .Release.Name }}-configmap
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
