{{- if .Values.createRoute }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ocp-deployment.labels" . | nindent 4 }}
    app.kubernetes.io/instance: ado-spring-demo
    app.kubernetes.io/name: ocp-deployment
    app.kubernetes.io/version: 1.16.0
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: ado-spring-demo-ocp-deployment
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
{{- end }}

